version: '2'
services: 
    server:
        build: gallery-filter-server
        ports: 
            - 80:8080
        environment: 
            APP_ENGINE_LOCATION: http://engine:5000
            APP_URL: http://localhost
            TWITTER_APIKEY:
            TWITTER_APISECRET:
        image: ${ECR_NAME}gallery-filter-server:0.0.1
    engine:
        build: gallery-filter-engine
        image: ${ECR_NAME}gallery-filter-engine:0.0.1